import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "@/provider/convex-client-provider";
import clsx from "clsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx('dark bg-gradient-to-br from-indigo-900 via-indigo-800 to-purple-900',inter.className)}>
        <ConvexClientProvider>
          {children}
          </ConvexClientProvider>
      </body>
    </html>
  );
}
